---
- hosts: all
  become: yes
  vars_files:
    - roles/linux/defaults/main.yml
    - roles/api/defaults/main.yml
    - roles/apps/defaults/main.yml
    - roles/sandman/defaults/main.yml
    - roles/apacheds/defaults/main.yml
    - roles/pwm/defaults/main.yml
  roles:
    - common
    - auth
